Add local Makefile for automated code updates
projectcalico/api pull request #48
Opened 2022-01-19 20:35 UTC by caseydavenport

## Description

Adds a Makefile target to run which will mirror api code from the
source-of-truth in github.com/projectcalico/calico/api

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

2022-01-20 09:30 UTC, fasaxc requested changes

2022-01-20 09:30 UTC, fasaxc commented on Makefile.local
> +	rm -rf /tmp/calico-api-mirror
Worth a check at the start that the repo isn't dirty?

2022-01-20 09:30 UTC, fasaxc commented on Makefile.local
> +	cp -r /tmp/calico-api-mirror/api/. .
Doesn't handle the case of a file being deleted, I think.

2022-01-20 09:34 UTC, fasaxc commented on Makefile.local
> +	cp -r /tmp/calico-api-mirror/api/. .
I might have reached for `git read-tree` or something after pulling the monorepo as a remote.  But on reflection, why use an arcane incantation when `cp` will do :laughing:

2022-01-25 23:27 UTC, caseydavenport commented
There's still a manual component to this, which is reviewing the changes that get pulled over and adding any to git tracking that need to be. But I think that's acceptable for now. We really just need something quick and dirty we can do for each minor release.

2022-01-28 22:09 UTC, merged